apiVersion: v1
kind: Service
metadata:
  name: llama-server
  labels:
    app.kubernetes.io/name: llama-server
spec:
  selector:
    app.kubernetes.io/name: llama-server
  ports:
    - name: http
      port: 80
      targetPort: http
