apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - http-route.yaml
patches:
  - path: gateway-access-patch.yaml
images:
  - name: ghcr.io/griffinseibold/hello-crud
    newTag: 0.2.0
