apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-crud-data
  labels:
    app.kubernetes.io/name: hello-crud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
